
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "/Users/ben/github/", "/vagrant/github"

  config.vm.network "forwarded_port", guest: 8080, host: 9000
  config.vm.network "forwarded_port", guest: 9000, host: 9002
  config.vm.network "forwarded_port", guest: 8000, host: 9001

  config.vm.box_check_update = false
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
    vmware.allowlist_verified = true
  end

end
