
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "/Users/ben/github/", "/vagrant/github"


  config.vm.box_check_update = false
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
    vmware.allowlist_verified = true
  end

end
