Vagrant.configure("2") do |config|  
  config.vm.provision :shell, path: "bootstrap.sh"
  #config.vm.network "private_network", ip: "10.45.42.12"

  #config.vm.synced_folder "/Users/ben/GitHub", "/vagrant/github", disabled: false, type:"virtualbox"
  config.vm.synced_folder "/Users/ben/github", "/vagrant/github"

  config.vm.network "forwarded_port", guest: 8080, host: 9000
  config.vm.network "forwarded_port", guest: 9000, host: 9002
  config.vm.network "forwarded_port", guest: 8000, host: 9001


  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
    # Uncomment to force arm64 for testing images on Intel
    # docker.create_args = ["--platform=linux/arm64"]     
  end

end