Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/noble64"
    
    # call installation script
    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.synced_folder "/Users/ben/github/", "/vagrant/github"

    config.vm.network "forwarded_port", guest: 8080, host: 8080

end
