Vagrant.configure("2") do |config| 
  config.vm.box = "" # choose a box type for your requirement
  config.vm.box_version = ""  # specify box version
  config.vm.box_check_update = false
  config.vm.provider "vmware_desktop" do |vmware|
  vmware.gui = false
  vmware.allowlist_verified = true
end
end