# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-2204-arm64"
  config.vm.synced_folder "/Users/ben/github/", "/vagrant/github", type: "rsync", rsync__auto: true

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network "forwarded_port", guest: 8080, host: 9015
  config.vm.network "forwarded_port", guest: 9000, host: 9003
  config.vm.network "forwarded_port", guest: 8000, host: 9016

  #vagrant rsync-auto

  config.vm.provider "qemu" do |qe|
    #qe.qemu_dir = "/vagrant/github"
    #qe.machine = "virt,accel=hvf,highmem=off"
    #qe.cpu = "cortex-a72"
  end

end
