Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/hirsute64"
  config.vm.box = "debian/bullseye64"

  config.vbguest.auto_update = false
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.50"

  #config.vm.synced_folder "/Users/ben/GitHub", "/vagrant/github", disabled: false, type:"virtualbox"
  config.vm.synced_folder "/Users/ben/GitHub", "/vagrant/github"

  config.vm.network "forwarded_port", guest: 27017, host: 9500
  config.vm.network "forwarded_port", guest: 27018, host: 9501
  config.vm.network "forwarded_port", guest: 27019, host: 9502

end