
Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "generic/alpine318"
  config.vm.box = "bento/ubuntu-22.04-arm64"

  

  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "/Users/ben/github/", "/vagrant/github"


  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    #vb.allowlist_verified = true
  end

end
