Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
    
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    #config.vm.network "forwarded_port", guest: 3000, host: 3000
    #config.vm.network "forwarded_port", guest: 3000, host: 3000

    config.vm.synced_folder "/Users/ben/GitHub/vagrant-photo-booth-service/", "/vagrant/photo-booth"

    #config.vm.provision :shell, :inline => "cd /vagrant/web-service/ && sudo mvn -Dspring-boot.run.jvmArguments=\"-Dspring.config.location=/vagrant/web-service.yml\" spring-boot:run", run: "always"
    #config.vm.provision :shell, :inline => "cd /vagrant/web-app/ && npm install && nam start" spring-boot:run", run: "always"
    
    #UUID:               639f4b65-74c2-49e0-9c21-322c655c52c4
    #VendorId:           0x04a9 (04A9)
    #ProductId:          0x3215 (3215)
    #Revision:           0.2 (0002)
    #Port:               3
    #USB version/speed:  0/High
    #Manufacturer:       Canon Inc.
    #Product:            Canon Digital Camera
    #Address:            p=0x3215;v=0x04a9;s=0x000130dd71be9a9c;l=0x14123000
    #Current State:      Available

    config.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--usb', 'on']
        vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'Canon', '--vendorid', '0x04a9', '--productid', '0x3215']
    end

end
