
spring:
 profiles.active: default
---
spring:
 profiles: default
 main:
  banner-mode: "off"
server:
 port: 8080
config:
 loading-picture-folder-path: "/vagrant/resources/loading"
 picture-folder-path: "/vagrant/output" 
 compressed-picture-folder-path: "/vagrant/output/compressed" 
logging:
 level:
  org:
   hibernate:
    SQL: DEBUG
    type:
     descriptor:
      sql:
       BasicBinder: TRACE
 