Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    #config.vm.box = "debian/jessie64"
    
    # call installation script
    config.vm.provision :shell, path: "bootstrap.sh"

    #config.vm.synced_folder "/Users/ben/temp/playground/muh/", "/vagrant/muh"

    config.vm.network "forwarded_port", guest: 8080, host: 8080

end
