Vagrant.configure("2") do |config|
  #config.vm.box = "debian/bullseye64"
  config.vm.box = "archlinux/archlinux"

  
  #config.vbguest.auto_update = false
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.30"

  config.vm.synced_folder "./data", "/data", disabled: false

  config.vm.network "forwarded_port", guest: 5432, host: 5432

end