Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  config.vbguest.auto_update = false
  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.30"

  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.network "forwarded_port", guest: 3306, host: 3306

end