Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/hirsute64"
  config.vm.box = "ubuntu/focal64"

  config.vbguest.auto_update = false
  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.201"

  config.vm.synced_folder "/Users/ben/temp/_vmshare", "/vagrant/github"

  #vagrant plugin install vagrant-proxyconf
  config.proxy.http     = "http://192.168.1.253:8201"
  config.proxy.https    = "http://192.168.1.253:8201"
  config.proxy.no_proxy = "localhost,127.0.0.1"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

end