Vagrant.configure("2") do |config|
  #config.vm.box = "debian/bullseye64"
  #config.vm.box = "debian/bookworm64"
  config.vm.box = "ubuntu/noble64"

  #config.vbguest.auto_update = false
  config.vm.provision :shell, path: "bootstrap.sh"
  #config.vm.network "private_network", ip: "10.45.42.12"

  #config.vm.synced_folder "/Users/ben/GitHub", "/vagrant/github", disabled: false, type:"virtualbox"
  config.vm.synced_folder "/Users/ben/github", "/vagrant/github"
  #config.vm.synced_folder "/Users/ben/Downloads/test", "/vagrant/test"

  #config.vm.network "forwarded_port", guest: 8080, host: 9000
  #config.vm.network "forwarded_port", guest: 9000, host: 9002
  #config.vm.network "forwarded_port", guest: 8000, host: 9001


  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    #docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
  end

end