Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    #config.vm.box = "debian/jessie64"
    
    # call installation script
    config.vm.provision :shell, path: "bootstrap.sh"

    #config.vm.synced_folder "/Users/ben/GitHub/emma-webservice", "/vagrant/emma-webservice"
    #config.vm.synced_folder "/Users/ben/GitHub/emma-webservice-spring", "/vagrant/emma-webservice-spring"
    #config.vm.synced_folder "/Users/ben/GitHub/tim-webservice", "/vagrant/tim-webservice"

    config.vm.network "forwarded_port", guest: 9999, host: 9999

end
