Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    #config.vm.box = "debian/jessie64"
    
    # call installation script
    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.network "forwarded_port", guest: 7474, host: 7474
    config.vm.network "forwarded_port", guest: 7687, host: 7687

    config.vm.synced_folder "/Users/ben/temp/neo4j_strore", "/vagrant/neo4j_strore"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2560
        vb.cpus = 2
    end

end
