Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.10"

  config.vm.synced_folder "/Users/ben/GitHub/emma-webapp-dev", "/vagrant/emma-webapp-dev"

  config.vm.network "forwarded_port", guest: 8080, host: 9000
  config.vm.network "forwarded_port", guest: 9000, host: 9002
  config.vm.network "forwarded_port", guest: 8000, host: 9001

end