Vagrant.configure("2") do |config|
    #config.vm.box = "archlinux/archlinux"
    config.vm.box = "debian/buster64"
  
    config.vm.provision :shell, path: "bootstrap.sh"

    if ENV['FIRST_RUN'] == 'true'
        config.vbguest.auto_update = false
        config.vm.synced_folder ".", "/vagrant", disabled: true
      else
        config.vm.synced_folder ".", "/vagrant", create: true, type: "virtualbox"
      end

    #config.vm.synced_folder "/Users/ben/temp/playground/vagrant-fuseki/config", "/vagrant/fuseki-config"
    config.vm.network "forwarded_port", guest: 3030, host: 3030
    
end