Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "10.45.42.20"

  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.network "forwarded_port", guest: 3030, host: 3030

end